// lang.js · every word the Hub shows, in English and Spanish.
// The code never contains a sentence; it asks for one by key.
window.LANG = {
  en: {
    appName: 'Colorado Referees',
    signinTitle: 'Sign in',
    signinLead: 'Use the email address on your referee record.',
    email: 'Your email address',
    sendCode: 'Email me a code',
    sending: 'Sending your code...',
    codeSent: 'Check your email for a 6-digit code. It is good for 10 minutes.',
    codeLabel: 'The code we emailed you',
    signIn: 'Sign in',
    noRecord: 'We could not find a referee record with that email. Use the address on your Learning Center account, or ask at Referee HQ.',
    tooMany: 'Too many codes sent just now. Wait a few minutes and try again.',
    couldNotSend: 'Could not send a code: ',
    badCode: 'That code did not work. Check the digits and try again.',
    wholeCode: 'Type the whole code from the email.',
    greeting: { morning: 'Good morning', afternoon: 'Good afternoon', evening: 'Good evening' },
    minutesToKickoff: 'minutes<br>to kickoff',
    hoursToKickoff: 'hours<br>to kickoff',
    kickedOff: 'kicked off',
    minAgo: 'minutes ago',
    noGamesToday: 'No games on your record today.',
    noGamesHint: 'When Assignr publishes your next game it shows here. Until then, the Library is a good place to be.',
    nextGame: 'Your next game',
    youAre: 'You are the',
    role: { cr: 'referee', ar1: 'assistant referee 1', ar2: 'assistant referee 2', fourth: 'fourth official' },
    checkIn: 'CHECK IN',
    checkingIn: 'Checking in...',
    checkedIn: 'CHECKED IN',
    checkedInAt: 'Staff can see you are here.',
    checkinFailed: 'Could not check in. Your tap is saved; tap again when you have signal, or check in at Referee HQ.',
    checkinWhere: 'Check in at Referee HQ when you arrive.',
    details: 'Details',
    laterToday: 'Later today',
    noteFrom: 'after',
    allNotes: 'All your notes',
    noNotes: 'No feedback yet. When a coach or mentor watches one of your games, their note lands here.',
    fromState: 'From Colorado Soccer',
    rules: 'Rules',
    map: 'Map',
    help: 'I NEED HELP',
    yourDay: 'Your day',
    back: 'Back',
    kicksIn: 'Kicks off in',
    home: 'Home, in dark',
    away: 'Away, in light',
    crew: 'Your crew',
    alone: 'This is your game alone; no assistants at this format.',
    afterGame: 'AFTER THE GAME',
    reportScore: 'Report the score',
    reportScoreHint: 'Two taps, then hand the game card to HQ',
    incident: 'File an incident report',
    incidentHint: 'A written report, in your words, for a send-off, dismissal or anything unusual',
    incidentNote: 'A report is read by the referee department; it does not page anyone. If something is happening right now, use I NEED HELP. Cautions and send-offs also go in your Assignr game report, as always.',
    comingSoon: 'Coming soon here. For now, use the current page.',
    helpTitle: "WHAT'S GOING ON?",
    helpLead: 'Pick one. It goes to Referee HQ with your name and field. Nothing sends until you confirm.',
    reasons: {
      roster: 'Roster or game card problem',
      spectator: 'Coach or spectator problem',
      redcard: 'Red card or send-off',
      fight: 'Fight or threat',
      injury: 'Injury, I need the trainer'
    },
    hotline: 'Text the Referee Hotline',
    groupUrgent: 'Texts the Site Coordinator and staff at your site right now',
    groupQueue: 'A message to Referee HQ',
    groupHotline: 'No staff where you are, or something else',
    hotlineDesktop: 'Text the Referee Hotline from your phone:',
    hotlineNote: 'A Referee Coach watches the hotline all day, every day. Use it when there is no Site Coordinator where you are, or for anything not on this list.',
    youPicked: 'You picked',
    goesTo: 'Texts the Site Coordinator and everyone who can respond at your site right now.',
    goesToQueue: 'Goes to Referee HQ as a message.',
    sendIt: 'SEND IT',
    neverMind: 'Never mind',
    sendingHelp: 'Sending...',
    helpSent: 'Sent. Referee HQ has it.',
    helpSentAt: 'Sent at',
    helpFailed: 'Could not send. Text the hotline instead:',
    helpFoot: 'If the site has no staff signed in, everything here goes to the hotline instead.',
    coachingEntry: 'Coaching',
    coachingEntryHint: 'Watch a game and leave a note',
    coachingTitle: 'COACHING',
    coachingLead: 'Pick where you are. Every game there is listed; tap one to write a note on a referee.',
    noVenuesToday: 'No games anywhere today.',
    venue: 'Venue',
    myNotes: 'My notes',
    myNotesLead: 'What you wrote, and what it became after cleanup. You always see both.',
    noMyNotes: 'You have not written a note yet.',
    crewPick: 'Who did you watch?',
    noteLabel: 'Your note',
    notePlaceholder: 'What you saw, what was good, one thing to work on. Write it like you would say it.',
    areaLabel: 'Which area does this speak to? (optional)',
    areas: { laws: 'Laws', reading: 'Reading the game', fitness: 'Fitness', presence: 'How you carry yourself' },
    saveNote: 'SAVE NOTE',
    savingNote: 'Saving...',
    noteSaved: 'Saved and signed',
    noteSavedHint: 'It goes to cleanup next, then to the Director of Referee Development. You can see it any time under My notes.',
    noteFailed: 'Could not save. Your words are still here; tap again when you have signal.',
    another: 'Note another referee on this game',
    rawLabel: 'What you wrote',
    cleanLabel: 'After cleanup',
    notCleaned: 'Not cleaned yet',
    status: { pending: 'Waiting for cleanup', cleaned: 'Cleaned, waiting for approval', approved: 'Approved, sent to the referee', edited: 'Approved, sent to the referee', rejected: 'Not sent' },
    signedAs: 'Signed as',
    reviewEntry: 'Notes to review',
    reviewEntryHint: 'Clean, approve and release feedback to referees',
    reviewTitle: 'REVIEW',
    reviewLead: 'Every note a coach wrote: what they wrote, what cleanup made of it, what the referee will get. Clean what is waiting, read it, approve to release. A released note reaches the referee in their Hub at once, and the coach sees all three versions.',
    filterPending: 'Waiting',
    filterCleaned: 'Cleaned',
    filterApproved: 'Approved',
    loadingReview: 'Loading notes...',
    nothingHere: 'Nothing here.',
    cleanBtn: 'Clean this note',
    cleanAll: 'Clean all waiting',
    cleaning: 'Cleaning...',
    approveBtn: 'APPROVE AND RELEASE',
    approveAll: 'Approve and release all cleaned',
    approving: 'Approving...',
    approved: 'Approved',
    approvedBy: 'by',
    flaggedNote: 'Flagged by cleanup: read before approving',
    reviewFailed: 'That did not go through. Try again.',
    notAllowed: 'Your titles do not open Review.',
    count: { one: '1 note', many: '{n} notes' },
    notSeen: 'Not seen yet',
    notSeenLong: 'Nobody has left this referee a note yet. Yours would be the first.',
    seenTimes: 'Seen {n} times, last',
    alreadySaid: 'Already said about this referee ({n} released notes). Add to it, do not repeat it.',
    redMeans: 'A name in red has had no feedback yet. Those are the ones to see first.',
    aiLabel: 'After cleanup',
    releasedLabel: 'Sent to the referee',
    notReleased: 'Not released yet',
    readBy: 'Read by the referee on',
    centerEntry: 'Command Center',
    centerEntryHint: 'Coverage, coaches, and the AI coach for coaches',
    centerTitle: 'REFEREE DEVELOPMENT',
    centerLead: 'Who has been seen, who has not, what the coaches are doing, and help for the coaches themselves.',
    tabCoverage: 'Coverage',
    tabCoaches: 'Coaches',
    tabAi: 'AI coach',
    tabQueue: 'Queue',
    stWorked: 'referees working this season',
    stSeen: 'seen at least once',
    stNever: 'never seen',
    stRead: 'released notes read',
    neverSeenTitle: 'Never seen, most games first',
    seenOnce: 'Seen once',
    gamesWorked: 'games',
    lastGame: 'last game',
    coachesTitle: 'Coaches and mentors, last 30 days',
    coachNotes: 'notes',
    coachRefs: 'referees',
    coachReleased: 'released',
    coachRead: 'read',
    noCoachActivity: 'No notes in the last 30 days.',
    aiLead: 'Reads every note a coach wrote in a date range and drafts a short, kind message to each coach: what landed well, what to tighten, how to give the referee more in fewer words. Nothing sends until you tap Send.',
    aiFrom: 'From',
    aiTo: 'To',
    aiRun: 'DRAFT COACHING NOTES',
    aiRunning: 'Reading the notes and drafting...',
    aiNone: 'No notes in that range.',
    aiSend: 'Send to',
    aiSending: 'Sending...',
    aiSent: 'Sent',
    aiNoEmail: 'No email on file for this coach',
    aiFailed: 'That did not go through.',
    queueWaiting: 'waiting for cleanup',
    queueCleaned: 'cleaned, ready to release',
    openReview: 'Open Review',
    opsEntry: 'The board',
    opsEntryHint: 'Every venue, crew and check-in today, live',
    opsTitle: 'THE BOARD',
    opsLead: 'Every venue with games on the day. Green is checked in. Red is a Help call still open.',
    tabBoard: 'Board',
    tabRetain: 'Retain',
    tabBulletins: 'Bulletins',
    stVenues: 'venues',
    stGames: 'games',
    stCheckedIn: 'checked in',
    stHelpOpen: 'help open',
    noGamesDay: 'No games on this day.',
    allVenues: 'All venues',
    helpOpenAt: 'Help open',
    ackInOld: 'Acknowledge Help calls in the current Command Center for now.',
    retainLead: 'Referees who are working but nobody has seen, and referees who have gone quiet.',
    retainNever: 'Working, never seen (3+ games)',
    retainQuiet: 'No game in 30 days',
    noneHere: 'Nobody here. Good.',
    bulletinsLead: 'What every referee sees on Your day. Live ones are in their date window.',
    bulletinLive: 'Live',
    bulletinOver: 'Over',
    bulletinFuture: 'Scheduled',
    newBulletin: 'New bulletin',
    bulTitle: 'Title',
    bulBody: 'Message',
    bulFrom: 'From',
    bulTo: 'To',
    bulPost: 'POST',
    bulPosting: 'Posting...',
    bulPosted: 'Posted. Referees see it now.',
    bulClear: 'Take down',
    bulCleared: 'Taken down',
    ackEnroute: 'On my way',
    ackHandled: 'Handled',
    change: 'Change',
    fieldLabel: 'Field',
    saveChanges: 'SAVE CHANGES',
    saving: 'Saving...',
    peopleEntry: 'People',
    peopleEntryHint: 'Find anyone, give or remove a Colorado title',
    peopleTitle: 'PEOPLE',
    peopleLead: 'Type a name. Titles from the Learning Center come in on their own and cannot be changed here. Colorado titles are yours to give.',
    peopleSearch: 'Search by name',
    noMatch: 'No one by that name.',
    lcTitles: 'From the Learning Center',
    coTitles: 'Colorado titles',
    addTitle: 'Add a title',
    remove: 'Remove',
    greenBadge: 'Green badge (under 18)',
    titleGiven: 'Added',
    titleTaken: 'Removed',
    noneYet: 'None yet',
    signOut: 'Sign out',
    builtWith: 'Built with JAReferee',
    theme: 'Switch between light and dark',
    langSwitch: 'Español'
  },
  es: {
    appName: 'Árbitros de Colorado',
    signinTitle: 'Iniciar sesión',
    signinLead: 'Usa el correo electrónico de tu registro de árbitro.',
    email: 'Tu correo electrónico',
    sendCode: 'Envíame un código',
    sending: 'Enviando tu código...',
    codeSent: 'Revisa tu correo: te enviamos un código de 6 dígitos. Vale por 10 minutos.',
    codeLabel: 'El código que te enviamos',
    signIn: 'Entrar',
    noRecord: 'No encontramos un registro de árbitro con ese correo. Usa el correo de tu cuenta del Learning Center, o pregunta en la carpa de árbitros.',
    tooMany: 'Se enviaron demasiados códigos. Espera unos minutos e inténtalo de nuevo.',
    couldNotSend: 'No se pudo enviar el código: ',
    badCode: 'Ese código no funcionó. Revisa los dígitos e inténtalo de nuevo.',
    wholeCode: 'Escribe el código completo del correo.',
    greeting: { morning: 'Buenos días', afternoon: 'Buenas tardes', evening: 'Buenas noches' },
    minutesToKickoff: 'minutos<br>para el inicio',
    hoursToKickoff: 'horas<br>para el inicio',
    kickedOff: 'inició hace',
    minAgo: 'minutos',
    noGamesToday: 'No tienes partidos hoy.',
    noGamesHint: 'Cuando Assignr publique tu próximo partido, aparecerá aquí. Mientras tanto, la Biblioteca es un buen lugar.',
    nextGame: 'Tu próximo partido',
    youAre: 'Eres',
    role: { cr: 'el árbitro central', ar1: 'el asistente 1', ar2: 'el asistente 2', fourth: 'el cuarto árbitro' },
    checkIn: 'REGISTRARME',
    checkingIn: 'Registrando...',
    checkedIn: 'REGISTRADO',
    checkedInAt: 'El personal ya sabe que llegaste.',
    checkinFailed: 'No se pudo registrar. Guardamos tu toque; inténtalo cuando tengas señal, o regístrate en la carpa de árbitros.',
    checkinWhere: 'Regístrate en la carpa de árbitros al llegar.',
    details: 'Detalles',
    laterToday: 'Más tarde hoy',
    noteFrom: 'después de',
    allNotes: 'Todas tus notas',
    noNotes: 'Aún no hay comentarios. Cuando un coach o mentor vea uno de tus partidos, su nota aparecerá aquí.',
    fromState: 'De Colorado Soccer',
    rules: 'Reglas',
    map: 'Mapa',
    help: 'NECESITO AYUDA',
    yourDay: 'Tu día',
    back: 'Atrás',
    kicksIn: 'Inicia en',
    home: 'Local, de oscuro',
    away: 'Visitante, de claro',
    crew: 'Tu equipo arbitral',
    alone: 'Este partido es solo tuyo; no hay asistentes en este formato.',
    afterGame: 'DESPUÉS DEL PARTIDO',
    reportScore: 'Reportar el marcador',
    reportScoreHint: 'Dos toques, luego entrega la hoja del partido en la carpa',
    incident: 'Presentar un reporte de incidente',
    incidentHint: 'Un reporte escrito, con tus palabras, para una expulsión, un despido o cualquier cosa inusual',
    incidentNote: 'El departamento de árbitros lee los reportes; no alertan a nadie de inmediato. Si algo está pasando ahora mismo, usa NECESITO AYUDA. Las amonestaciones y expulsiones también van en tu reporte de Assignr, como siempre.',
    comingSoon: 'Pronto estará aquí. Por ahora, usa la página actual.',
    helpTitle: '¿QUÉ ESTÁ PASANDO?',
    helpLead: 'Elige una opción. Llega a la carpa de árbitros con tu nombre y tu cancha. No se envía nada hasta que confirmes.',
    reasons: {
      roster: 'Problema con la lista o la hoja del partido',
      spectator: 'Problema con un entrenador o espectador',
      redcard: 'Tarjeta roja o expulsión',
      fight: 'Pelea o amenaza',
      injury: 'Lesión, necesito al entrenador médico'
    },
    hotline: 'Enviar texto a la línea de árbitros',
    groupUrgent: 'Envía un texto ahora mismo al coordinador de sede y al personal de tu sede',
    groupQueue: 'Un mensaje a la carpa de árbitros',
    groupHotline: 'Sin personal donde estás, u otra cosa',
    hotlineDesktop: 'Escribe a la línea de árbitros desde tu teléfono:',
    hotlineNote: 'Un Referee Coach vigila la línea todo el día, todos los días. Úsala cuando no haya coordinador de sede donde estás, o para cualquier cosa que no esté en esta lista.',
    youPicked: 'Elegiste',
    goesTo: 'Envía un texto al coordinador de sede y a todos los que puedan responder en tu sede ahora mismo.',
    goesToQueue: 'Llega a la carpa de árbitros como mensaje.',
    sendIt: 'ENVIAR',
    neverMind: 'Olvídalo',
    sendingHelp: 'Enviando...',
    helpSent: 'Enviado. La carpa de árbitros ya lo tiene.',
    helpSentAt: 'Enviado a las',
    helpFailed: 'No se pudo enviar. Escribe a la línea de árbitros:',
    helpFoot: 'Si la sede no tiene personal conectado, todo esto va a la línea de árbitros.',
    coachingEntry: 'Coaching',
    coachingEntryHint: 'Observa un partido y deja una nota',
    coachingTitle: 'COACHING',
    coachingLead: 'Elige dónde estás. Se listan todos los partidos de ahí; toca uno para escribir una nota sobre un árbitro.',
    noVenuesToday: 'No hay partidos en ningún lugar hoy.',
    venue: 'Sede',
    myNotes: 'Mis notas',
    myNotesLead: 'Lo que escribiste, y en qué se convirtió tras la limpieza. Siempre ves ambos.',
    noMyNotes: 'Aún no has escrito una nota.',
    crewPick: '¿A quién observaste?',
    noteLabel: 'Tu nota',
    notePlaceholder: 'Lo que viste, lo que estuvo bien, una cosa para trabajar. Escríbelo como lo dirías.',
    areaLabel: '¿A qué área se refiere? (opcional)',
    areas: { laws: 'Reglas', reading: 'Lectura del juego', fitness: 'Condición física', presence: 'Cómo te presentas' },
    saveNote: 'GUARDAR NOTA',
    savingNote: 'Guardando...',
    noteSaved: 'Guardada y firmada',
    noteSavedHint: 'Ahora pasa a limpieza y luego al Director de Desarrollo de Árbitros. Puedes verla cuando quieras en Mis notas.',
    noteFailed: 'No se pudo guardar. Tus palabras siguen aquí; toca de nuevo cuando tengas señal.',
    another: 'Anotar a otro árbitro de este partido',
    rawLabel: 'Lo que escribiste',
    cleanLabel: 'Tras la limpieza',
    notCleaned: 'Aún sin limpiar',
    status: { pending: 'Esperando limpieza', cleaned: 'Limpia, esperando aprobación', approved: 'Aprobada, enviada al árbitro', edited: 'Aprobada, enviada al árbitro', rejected: 'No enviada' },
    signedAs: 'Firmada como',
    reviewEntry: 'Notas por revisar',
    reviewEntryHint: 'Limpia, aprueba y entrega comentarios a los árbitros',
    reviewTitle: 'REVISIÓN',
    reviewLead: 'Cada nota que escribió un coach, original junto a limpia. Limpia las pendientes, lee ambas, aprueba las listas. Las aprobadas llegan al árbitro en su Hub de inmediato.',
    filterPending: 'En espera',
    filterCleaned: 'Limpias',
    filterApproved: 'Aprobadas',
    loadingReview: 'Cargando notas...',
    nothingHere: 'Nada por aquí.',
    cleanBtn: 'Limpiar esta nota',
    cleanAll: 'Limpiar todas las pendientes',
    cleaning: 'Limpiando...',
    approveBtn: 'APROBAR Y ENTREGAR',
    approveAll: 'Aprobar y entregar todas las limpias',
    approving: 'Aprobando...',
    approved: 'Aprobada',
    approvedBy: 'por',
    flaggedNote: 'Marcada por la limpieza: léela antes de aprobar',
    reviewFailed: 'No se pudo. Inténtalo de nuevo.',
    notAllowed: 'Tus títulos no abren Revisión.',
    count: { one: '1 nota', many: '{n} notas' },
    notSeen: 'Sin observar aún',
    notSeenLong: 'Nadie le ha dejado una nota a este árbitro todavía. La tuya sería la primera.',
    seenTimes: 'Observado {n} veces, la última',
    alreadySaid: 'Ya se dijo sobre este árbitro ({n} notas entregadas). Añade, no repitas.',
    redMeans: 'Un nombre en rojo no ha recibido comentarios aún. Esos van primero.',
    aiLabel: 'Tras la limpieza',
    releasedLabel: 'Entregada al árbitro',
    notReleased: 'Aún no entregada',
    readBy: 'Leída por el árbitro el',
    centerEntry: 'Centro de mando',
    centerEntryHint: 'Cobertura, coaches y el coach de IA para coaches',
    centerTitle: 'DESARROLLO ARBITRAL',
    centerLead: 'Quién ha sido observado, quién no, qué hacen los coaches y ayuda para los propios coaches.',
    tabCoverage: 'Cobertura',
    tabCoaches: 'Coaches',
    tabAi: 'Coach de IA',
    tabQueue: 'Cola',
    stWorked: 'árbitros activos esta temporada',
    stSeen: 'observados al menos una vez',
    stNever: 'nunca observados',
    stRead: 'notas entregadas leídas',
    neverSeenTitle: 'Nunca observados, más partidos primero',
    seenOnce: 'Observados una vez',
    gamesWorked: 'partidos',
    lastGame: 'último partido',
    coachesTitle: 'Coaches y mentores, últimos 30 días',
    coachNotes: 'notas',
    coachRefs: 'árbitros',
    coachReleased: 'entregadas',
    coachRead: 'leídas',
    noCoachActivity: 'Sin notas en los últimos 30 días.',
    aiLead: 'Lee cada nota que escribió un coach en un rango de fechas y redacta un mensaje corto y amable para cada coach: qué funcionó, qué ajustar, cómo dar más al árbitro en menos palabras. No se envía nada hasta que toques Enviar.',
    aiFrom: 'Desde',
    aiTo: 'Hasta',
    aiRun: 'REDACTAR NOTAS PARA COACHES',
    aiRunning: 'Leyendo las notas y redactando...',
    aiNone: 'No hay notas en ese rango.',
    aiSend: 'Enviar a',
    aiSending: 'Enviando...',
    aiSent: 'Enviado',
    aiNoEmail: 'Este coach no tiene correo registrado',
    aiFailed: 'No se pudo.',
    queueWaiting: 'esperando limpieza',
    queueCleaned: 'limpias, listas para entregar',
    openReview: 'Abrir Revisión',
    opsEntry: 'El tablero',
    opsEntryHint: 'Cada sede, equipo arbitral y registro de hoy, en vivo',
    opsTitle: 'EL TABLERO',
    opsLead: 'Cada sede con partidos ese día. Verde es registrado. Rojo es una llamada de ayuda abierta.',
    tabBoard: 'Tablero',
    tabRetain: 'Retener',
    tabBulletins: 'Avisos',
    stVenues: 'sedes',
    stGames: 'partidos',
    stCheckedIn: 'registrados',
    stHelpOpen: 'ayuda abierta',
    noGamesDay: 'No hay partidos ese día.',
    allVenues: 'Todas las sedes',
    helpOpenAt: 'Ayuda abierta',
    ackInOld: 'Por ahora, atiende las llamadas de ayuda en el centro de mando actual.',
    retainLead: 'Árbitros que trabajan pero nadie ha observado, y árbitros que han dejado de aparecer.',
    retainNever: 'Trabajando, nunca observados (3+ partidos)',
    retainQuiet: 'Sin partidos en 30 días',
    noneHere: 'Nadie aquí. Bien.',
    bulletinsLead: 'Lo que cada árbitro ve en Tu día. Los vigentes están dentro de su rango de fechas.',
    bulletinLive: 'Vigente',
    bulletinOver: 'Terminado',
    bulletinFuture: 'Programado',
    newBulletin: 'Nuevo aviso',
    bulTitle: 'Título',
    bulBody: 'Mensaje',
    bulFrom: 'Desde',
    bulTo: 'Hasta',
    bulPost: 'PUBLICAR',
    bulPosting: 'Publicando...',
    bulPosted: 'Publicado. Los árbitros ya lo ven.',
    bulClear: 'Retirar',
    bulCleared: 'Retirado',
    ackEnroute: 'Voy en camino',
    ackHandled: 'Resuelto',
    change: 'Cambiar',
    fieldLabel: 'Cancha',
    saveChanges: 'GUARDAR CAMBIOS',
    saving: 'Guardando...',
    peopleEntry: 'Personas',
    peopleEntryHint: 'Busca a cualquiera, da o quita un título de Colorado',
    peopleTitle: 'PERSONAS',
    peopleLead: 'Escribe un nombre. Los títulos del Learning Center llegan solos y no se cambian aquí. Los títulos de Colorado los das tú.',
    peopleSearch: 'Buscar por nombre',
    noMatch: 'Nadie con ese nombre.',
    lcTitles: 'Del Learning Center',
    coTitles: 'Títulos de Colorado',
    addTitle: 'Añadir un título',
    remove: 'Quitar',
    greenBadge: 'Insignia verde (menor de 18)',
    titleGiven: 'Añadido',
    titleTaken: 'Quitado',
    noneYet: 'Ninguno aún',
    signOut: 'Cerrar sesión',
    builtWith: 'Hecho con JAReferee',
    theme: 'Cambiar entre claro y oscuro',
    langSwitch: 'English'
  }
};
