// lang.js · every word the Hub shows, in English and Spanish.
// The code never contains a sentence; it asks for one by key.
window.LANG = {
  en: {
    appName: 'Colorado Referees',
    signinTitle: 'Sign in',
    signinLead: 'Use the email address on your referee record.',
    email: 'Your email address',
    sendCode: 'Email me a code',
    sending: 'Sending your code...',
    codeSent: 'Check your email for a 6-digit code. It is good for 10 minutes.',
    codeLabel: 'The code we emailed you',
    signIn: 'Sign in',
    noRecord: 'We could not find a referee record with that email. Use the address on your Learning Center account, or ask at Referee HQ.',
    tooMany: 'Too many codes sent just now. Wait a few minutes and try again.',
    couldNotSend: 'Could not send a code: ',
    badCode: 'That code did not work. Check the digits and try again.',
    wholeCode: 'Type the whole code from the email.',
    greeting: { morning: 'Good morning', afternoon: 'Good afternoon', evening: 'Good evening' },
    minutesToKickoff: 'minutes<br>to kickoff',
    hoursToKickoff: 'hours<br>to kickoff',
    kickedOff: 'kicked off',
    minAgo: 'minutes ago',
    noGamesToday: 'No games on your record today.',
    noGamesHint: 'When Assignr publishes your next game it shows here. Until then, the Library is a good place to be.',
    nextGame: 'Your next game',
    youAre: 'You are the',
    role: { cr: 'referee', ar1: 'assistant referee 1', ar2: 'assistant referee 2', fourth: 'fourth official' },
    checkIn: 'CHECK IN',
    checkingIn: 'Checking in...',
    checkedIn: 'CHECKED IN',
    checkedInAt: 'Staff can see you are here.',
    checkinFailed: 'Could not check in. Your tap is saved; tap again when you have signal, or check in at Referee HQ.',
    checkinWhere: 'Check in at Referee HQ when you arrive.',
    details: 'Details',
    laterToday: 'Later today',
    noteFrom: 'after',
    allNotes: 'All your notes',
    noNotes: 'No feedback yet. When a coach or mentor watches one of your games, their note lands here.',
    fromState: 'From Colorado Soccer',
    rules: 'Rules',
    map: 'Map',
    help: 'I NEED HELP',
    yourDay: 'Your day',
    back: 'Back',
    kicksIn: 'Kicks off in',
    home: 'Home, in dark',
    away: 'Away, in light',
    crew: 'Your crew',
    alone: 'This is your game alone; no assistants at this format.',
    afterGame: 'AFTER THE GAME',
    reportScore: 'Report the score',
    reportScoreHint: 'Two taps, then hand the game card to HQ',
    incident: 'File an incident report',
    incidentHint: 'A written report, in your words, for a send-off, dismissal or anything unusual',
    incidentNote: 'A report is read by the referee department; it does not page anyone. If something is happening right now, use I NEED HELP. Cautions and send-offs also go in your Assignr game report, as always.',
    comingSoon: 'Coming soon here. For now, use the current page.',
    helpTitle: "WHAT'S GOING ON?",
    helpLead: 'Pick one. It goes to Referee HQ with your name and field. Nothing sends until you confirm.',
    reasons: {
      roster: 'Roster or game card problem',
      spectator: 'Coach or spectator problem',
      redcard: 'Red card or send-off',
      fight: 'Fight or threat',
      injury: 'Injury, I need the trainer'
    },
    hotline: 'Text the Referee Hotline',
    groupUrgent: 'Texts the Site Coordinator and staff at your site right now',
    groupQueue: 'A message to Referee HQ',
    groupHotline: 'No staff where you are, or something else',
    hotlineDesktop: 'Text the Referee Hotline from your phone:',
    hotlineNote: 'A Referee Coach watches the hotline all day, every day. Use it when there is no Site Coordinator where you are, or for anything not on this list.',
    youPicked: 'You picked',
    goesTo: 'Texts the Site Coordinator and everyone who can respond at your site right now.',
    goesToQueue: 'Goes to Referee HQ as a message.',
    sendIt: 'SEND IT',
    neverMind: 'Never mind',
    sendingHelp: 'Sending...',
    helpSent: 'Sent. Referee HQ has it.',
    helpSentAt: 'Sent at',
    helpFailed: 'Could not send. Text the hotline instead:',
    helpFoot: 'If the site has no staff signed in, everything here goes to the hotline instead.',
    signOut: 'Sign out',
    builtWith: 'Built with JAReferee',
    theme: 'Switch between light and dark',
    langSwitch: 'Español'
  },
  es: {
    appName: 'Árbitros de Colorado',
    signinTitle: 'Iniciar sesión',
    signinLead: 'Usa el correo electrónico de tu registro de árbitro.',
    email: 'Tu correo electrónico',
    sendCode: 'Envíame un código',
    sending: 'Enviando tu código...',
    codeSent: 'Revisa tu correo: te enviamos un código de 6 dígitos. Vale por 10 minutos.',
    codeLabel: 'El código que te enviamos',
    signIn: 'Entrar',
    noRecord: 'No encontramos un registro de árbitro con ese correo. Usa el correo de tu cuenta del Learning Center, o pregunta en la carpa de árbitros.',
    tooMany: 'Se enviaron demasiados códigos. Espera unos minutos e inténtalo de nuevo.',
    couldNotSend: 'No se pudo enviar el código: ',
    badCode: 'Ese código no funcionó. Revisa los dígitos e inténtalo de nuevo.',
    wholeCode: 'Escribe el código completo del correo.',
    greeting: { morning: 'Buenos días', afternoon: 'Buenas tardes', evening: 'Buenas noches' },
    minutesToKickoff: 'minutos<br>para el inicio',
    hoursToKickoff: 'horas<br>para el inicio',
    kickedOff: 'inició hace',
    minAgo: 'minutos',
    noGamesToday: 'No tienes partidos hoy.',
    noGamesHint: 'Cuando Assignr publique tu próximo partido, aparecerá aquí. Mientras tanto, la Biblioteca es un buen lugar.',
    nextGame: 'Tu próximo partido',
    youAre: 'Eres',
    role: { cr: 'el árbitro central', ar1: 'el asistente 1', ar2: 'el asistente 2', fourth: 'el cuarto árbitro' },
    checkIn: 'REGISTRARME',
    checkingIn: 'Registrando...',
    checkedIn: 'REGISTRADO',
    checkedInAt: 'El personal ya sabe que llegaste.',
    checkinFailed: 'No se pudo registrar. Guardamos tu toque; inténtalo cuando tengas señal, o regístrate en la carpa de árbitros.',
    checkinWhere: 'Regístrate en la carpa de árbitros al llegar.',
    details: 'Detalles',
    laterToday: 'Más tarde hoy',
    noteFrom: 'después de',
    allNotes: 'Todas tus notas',
    noNotes: 'Aún no hay comentarios. Cuando un coach o mentor vea uno de tus partidos, su nota aparecerá aquí.',
    fromState: 'De Colorado Soccer',
    rules: 'Reglas',
    map: 'Mapa',
    help: 'NECESITO AYUDA',
    yourDay: 'Tu día',
    back: 'Atrás',
    kicksIn: 'Inicia en',
    home: 'Local, de oscuro',
    away: 'Visitante, de claro',
    crew: 'Tu equipo arbitral',
    alone: 'Este partido es solo tuyo; no hay asistentes en este formato.',
    afterGame: 'DESPUÉS DEL PARTIDO',
    reportScore: 'Reportar el marcador',
    reportScoreHint: 'Dos toques, luego entrega la hoja del partido en la carpa',
    incident: 'Presentar un reporte de incidente',
    incidentHint: 'Un reporte escrito, con tus palabras, para una expulsión, un despido o cualquier cosa inusual',
    incidentNote: 'El departamento de árbitros lee los reportes; no alertan a nadie de inmediato. Si algo está pasando ahora mismo, usa NECESITO AYUDA. Las amonestaciones y expulsiones también van en tu reporte de Assignr, como siempre.',
    comingSoon: 'Pronto estará aquí. Por ahora, usa la página actual.',
    helpTitle: '¿QUÉ ESTÁ PASANDO?',
    helpLead: 'Elige una opción. Llega a la carpa de árbitros con tu nombre y tu cancha. No se envía nada hasta que confirmes.',
    reasons: {
      roster: 'Problema con la lista o la hoja del partido',
      spectator: 'Problema con un entrenador o espectador',
      redcard: 'Tarjeta roja o expulsión',
      fight: 'Pelea o amenaza',
      injury: 'Lesión, necesito al entrenador médico'
    },
    hotline: 'Enviar texto a la línea de árbitros',
    groupUrgent: 'Envía un texto ahora mismo al coordinador de sede y al personal de tu sede',
    groupQueue: 'Un mensaje a la carpa de árbitros',
    groupHotline: 'Sin personal donde estás, u otra cosa',
    hotlineDesktop: 'Escribe a la línea de árbitros desde tu teléfono:',
    hotlineNote: 'Un Referee Coach vigila la línea todo el día, todos los días. Úsala cuando no haya coordinador de sede donde estás, o para cualquier cosa que no esté en esta lista.',
    youPicked: 'Elegiste',
    goesTo: 'Envía un texto al coordinador de sede y a todos los que puedan responder en tu sede ahora mismo.',
    goesToQueue: 'Llega a la carpa de árbitros como mensaje.',
    sendIt: 'ENVIAR',
    neverMind: 'Olvídalo',
    sendingHelp: 'Enviando...',
    helpSent: 'Enviado. La carpa de árbitros ya lo tiene.',
    helpSentAt: 'Enviado a las',
    helpFailed: 'No se pudo enviar. Escribe a la línea de árbitros:',
    helpFoot: 'Si la sede no tiene personal conectado, todo esto va a la línea de árbitros.',
    signOut: 'Cerrar sesión',
    builtWith: 'Hecho con JAReferee',
    theme: 'Cambiar entre claro y oscuro',
    langSwitch: 'English'
  }
};
